name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when there is a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git user information
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      env:
        REACT_APP_PASSWORD: ${{ secrets.REACT_APP_PASSWORD }}  
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        # Set the GitHub token for authentication
        git config --global url."https://$GH_TOKEN@github.com".insteadOf "https://github.com/"
        npm run deploy
